### ISSUE TITLE
Unable to set background gradient for uifigure

### ISSUE THREAD

**Issue by davidn-IA** [StackOverflowMATLABchat/mlapptools#10]
This may seem like pure greed to want to be able to do it, but it would be terrific if it were possible.  Something like this fails (edit: W10, 2017b):

mlapptools.setStyle(uifigure(),'background','linear-gradient(red, pink, white)')
Warning: This widget is unsupported. 
> In mlapptools/getWidgetID (line 386)
  In mlapptools.getWebElements (line 130)
  In mlapptools.setStyle (line 238) 
Output argument "ID_obj" (and maybe others) not
assigned during call to "mlapptools/getWidgetID".
Error in mlapptools.getWebElements (line 130)
                widgetID = mlapptools.getWidgetID(win,
                mlapptools.getDataTag(uiElement));
Error in mlapptools.setStyle (line 238)
                [win, ID_obj] =
                mlapptools.getWebElements(hControl);

**Comment by Dev-iL** [comment]
Resolved by #11 .

**Comment by sco1** [comment]
Cool!

I'm going to have to start a [Geocities-izer](http://www.wonder-tonic.com/geocitiesizer/) fork of this soon ;)
