### ISSUE TITLE
Fieldname update for matlab.internal.webwindow on R2017a

### ISSUE THREAD

**Issue by Dev-iL** [StackOverflowMATLABchat/mlapptools#2]
With reference to the following line:
https://github.com/StackOverflowMATLABchat/mlapptools/blob/74ce1e5ead81e00060cd888fe7bafb8f1c0225fc/mlapptools.m#L59

In R2017a this is required instead:
```matlab
struct(struct(struct(app.UIFigure).Controller).PlatformHost).CEF;
```

Opening an issue since I'm not sure what's the best way to have the correct code execute based on MATLAB version.

**Comment by sco1** [comment]
Thanks for the heads up! The simplest method is to use [`verlessthan`](https://www.mathworks.com/help/matlab/ref/verlessthan.html), I'll try to get it thrown in this morning.

**Comment by Dev-iL** [comment]
From private correspondence with Yair, it seems like this change was actually introduced in R2016b. I will try to verify this and update.
