### ISSUE TITLE
variable typo problem

### ISSUE THREAD

**Issue by rancohen2000** [StackOverflowMATLABchat/mlapptools#27]
## Summary
need to fix variable name on line 291 to: hUIElement

## Problem Description
matlab error: not found uiElement

## Specifications
  - MATLAB Release: R2018b
  - Operating System: Window 10
  - `mlapptools` version (or commit link/hash):

**Comment by Dev-iL** [comment]
תודה על הדיווח, יתוקן בהקדם!

**Comment by Dev-iL** [comment]
This was fixed by the commit above ^
